// Writes public/images/README.md: every image the site expects, where it goes,
// and whether it has been uploaded yet. Run with `npm run images`.
import { existsSync, writeFileSync } from 'node:fs'
import { aiEntries } from '../src/data/aiLab.js'
import { gallery } from '../src/data/gallery.js'
import { projects } from '../src/data/projects.js'
import { portrait } from '../src/data/site.js'

const sections = [
  ...projects.map((project) => ({ title: `Project — ${project.title}`, images: [project.cover, ...project.images] })),
  ...aiEntries.filter((entry) => entry.status !== 'soon').map((entry) => ({ title: `AI Lab — ${entry.title}`, images: [entry.cover, ...entry.images] })),
  { title: 'About', images: [{ src: portrait, caption: 'Portrait' }] },
  { title: 'Gallery', images: gallery }
]

let total = 0
let uploaded = 0
const lines = [
  '# Images',
  '',
  'Every image the site shows, with the exact path to upload it to. Until a file is uploaded, the site shows a plain, very light grey block in its place.',
  '',
  'Export JPG, about 2500–3000 px on the long side, ideally under 5 MB (Cloudflare Pages refuses files over 25 MB). Each project\'s `cover.jpg` is the image used on the home page, the Projects page and the top of the project page.',
  '',
  'This list is generated by `npm run images` from the files in `src/data/`.',
  ''
]

for (const section of sections) {
  lines.push(`## ${section.title}`, '', '| | File | Shows |', '|---|---|---|')
  for (const image of section.images) {
    const has = existsSync(new URL(`../public${image.src}`, import.meta.url))
    total += 1
    if (has) uploaded += 1
    lines.push(`| ${has ? '✓' : ' '} | \`public${image.src}\` | ${image.caption} |`)
  }
  lines.push('')
}

lines.splice(2, 0, `${uploaded} of ${total} uploaded.`, '')
writeFileSync(new URL('../public/images/README.md', import.meta.url), lines.join('\n'))
console.log(`${uploaded} of ${total} images uploaded; list written to public/images/README.md`)
